#!/bin/bash

## #ddev-generated: If you want to edit and own this file, remove this line.
## Description: Launch a browser with Portainer UI
## Usage: portainer
## Example: "ddev portainer"

ddev launch :9100

