name: Tests
on:
  pull_request:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'

  schedule:
    - cron: '25 0 * * *'

  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: Debug with tmate
        default: false
  workflow_run:
    types: [completed]
    workflows: [Create Release]


permissions:
  actions: write

jobs:
  tests:

    strategy:
      matrix:
        ddev_version: [stable, HEAD]
      fail-fast: false

    runs-on: ubuntu-latest
    if: |
        contains(fromJson('["push","pull_request","workflow_dispatch","schedule"]'), github.event_name) ||
        (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')

    steps:

      - uses: ddev/ddev-add-on-test@v2
        with:
          ddev_version: ${{ matrix.ddev_version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          debug_enabled: ${{ github.event.inputs.debug_enabled }}
          addon_repository: ${{ env.GITHUB_REPOSITORY }}
          addon_ref: ${{ env.GITHUB_REF }}

  workflow-keepalive:
    name: Keepalive workflow
    if: github.event_name == 'schedule'
    uses: ./.github/workflows/keepalive.yml
    permissions:
      actions: write
